import ImgProd from "./Img";

const ProductNow = [
  {
    id: 1,
    name: 'GILET JACQUARD CUORE LIMITED EDITION',
    href: '/ProductOverviews',
    price: '€39,95',
    imageSrc: ImgProd.GiletMBF,
    imageAlt: 'GILET JACQUARD CUORE LIMITED EDITION',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Gilet relaxed fit in maglia di filato di cotone. Scollo a V e giromanica. Finiture a coste.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.GiletMBF, alt: 'Image 1' },
      { src: ImgProd.GiletMBB, alt: 'Image 2' },
      { src: ImgProd.GiletMBC, alt: 'Image 3' },
      { src: ImgProd.GiletMBModel, alt: 'Image 4' },
    ],
  },
     {
    id: 2,
    name: 'MAGLIETTA CON STAMPA NOTE LIMITED EDITION',
    href: '/ProductOverviews',
    price: '€25,95',
    imageSrc: ImgProd.MagliettaMNF,
    imageAlt: 'GMAGLIETTA CON STAMPA NOTE LIMITED EDITION',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Maglietta boxy fit. Collo rotondo e maniche corte. Stampe di testi combinate con toppe anteriori e posteriori.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.MagliettaMNF, alt: 'Image 1' },
      { src: ImgProd.MagliettaMNB, alt: 'Image 2' },
      { src: ImgProd.MagliettaMNC, alt: 'Image 3' },
      { src: ImgProd.MagliettaMNModel, alt: 'Image 4' },
    ],
  },
  {
    id: 3,
    name: 'MAGLIETTA CON SCRITTA GOMMATA LIMITED EDITION',
    href: '/ProductOverviews',
    price: '€22,95',
    imageSrc: ImgProd.GiletMWF,
    imageAlt: 'MAGLIETTA CON SCRITTA GOMMATA LIMITED EDITION',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Giacca relaxed fit realizzata in tessuto misto lana leggermente imbottito all interno. Collo alto a coste in tinta e maniche lunghe. Tasche con chiusura a zip sui fianchi. Finiture a coste. Chiusura frontale con cerniera',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'T-shirt boxy fit. Collo rotondo e maniche corte. Stampe di scritte combinate a contrasto su fronte e retro.',
    images: [
      { src: ImgProd.GiletMWF, alt: 'Image 1' },
      { src: ImgProd.GiletMWB, alt: 'Image 2' },
      { src: ImgProd.GiletMWC, alt: 'Image 3' },
      { src: ImgProd.GiletMWModel, alt: 'Image 4' },
    ],
  },
  {
    id: 4,
    name: 'POLO',
    href: '/ProductOverviews',
    price: '€25,95',
    imageSrc: ImgProd.PoloTMF,
    imageAlt: 'GIUBBOTTO BOUCLÉ MISTO LANA',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Polo regular fit. Collo a revers con apertura frontale. Manica corta. Fondo con spacchi laterali.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.PoloTMF, alt: 'Image 1' },
      { src: ImgProd.PoloTMB, alt: 'Image 2' },
      { src: ImgProd.PoloTMC, alt: 'Image 3' },
      { src: ImgProd.PoloTMModel, alt: 'Image 4' },
    ],
  },
   {
    id: 5,
    name: 'GONNA IN PELLE CON PIZZO LIMITED EDITION',
    href: '/ProductOverviews',
    price: '€99,95',
    imageSrc: ImgProd.GonnaWBF,
    imageAlt: 'GONNA IN PELLE CON PIZZO LIMITED EDITION',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: false }, { name: 'L', inStock: true }, { name: 'XL', inStock: true }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'ProductList', href: '#' }],
    description: 'Gonna midi a vita media realizzata in pelle 100%. Dettaglio applicazione di pizzo combinato a contrasto. Chiusura laterale con cerniera nascosta nella cucitura.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.GonnaWBF, alt: 'Image 1' },
      { src: ImgProd.GonnaWBB, alt: 'Image 2' },
      { src: ImgProd.GonnaWBC, alt: 'Image 3' },
      { src: ImgProd.GonnaWBModel, alt: 'Image 4' },
    ],
  },
   {
    id: 6,
    name: 'VESTITO HALTER A GODET ZW COLLECTION',
    href: '/ProductOverviews',
    price: '€49,95',
    imageSrc: ImgProd.VestitoWWF,
    imageAlt: 'VESTITO HALTER A GODET ZW COLLECTION',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: true }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: true }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'ProductList', href: '#' }],
    description: 'Vestito corto con collo halter e spalle scoperte. Fondo a godet. Chiusura posteriore con cerniera nascosta nella cucitura.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.VestitoWWF, alt: 'Image 1' },
      { src: ImgProd.VestitoWWB, alt: 'Image 2' },
      { src: ImgProd.VestitoWWC, alt: 'Image 3' },
      { src: ImgProd.VestitoWWModel, alt: 'Image 4' },
    ],
  },
   {
    id: 7,
    name: 'STIVALI IN PELLE CON TACCO E TIRANTE',
    href: '/ProductOverviews',
    price: '€119,00',
    imageSrc: ImgProd.StivaliWBF,
    imageAlt: 'STIVALI IN PELLE CON TACCO E TIRANTE',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: '37', inStock: false }, { name: '38', inStock: false }, { name: '39', inStock: true }, { name: '40', inStock: true }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'Scarpe', href: '#' }],
    description: 'Stivale in pelle. Gamba larga. Dettaglio di impunture sulla tomaia. Dettaglio di tirante sul retro. Tacco medio largo. Punta tonda.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.StivaliWBF, alt: 'Image 1' },
      { src: ImgProd.StivaliWBB, alt: 'Image 2' },
      { src: ImgProd.StivaliWBC, alt: 'Image 3' },
      { src: ImgProd.StivaliWBModel, alt: 'Image 4' },
    ],
  },
   {
    id: 8,
    name: 'SCARPE DA RUNNING CON RETE',
    href: '/ProductOverviews',
    price: '€59,95',
    imageSrc: ImgProd.ScarpeWBF,
    imageAlt: 'CAPPOTTO MANTELLA IN MAGLIA',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: '37', inStock: true }, { name: '38', inStock: true }, { name: '39', inStock: true }, { name: '40', inStock: true }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'Scarpe', href: '#' }],
    description: 'Cappotto realizzato in filato misto lana. Colletto con revers classici e maniche lunghe. Tasche con patta sul davanti e a.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.ScarpeWBF, alt: 'Image 1' },
      { src: ImgProd.ScarpeWBB, alt: 'Image 2' },
      { src: ImgProd.ScarpeWBC, alt: 'Image 3' },
      { src: ImgProd.ScarpeWBModel, alt: 'Image 4' },
    ],
  },
  // Agrega más productos aquí...
];

export default ProductNow;