import ImgProd from "../Components/Img"; // Asegúrate de que la ruta sea correcta

const ProductList = [
  {
    id: 1,
    name: 'GIACCA CON RICAMO DI PERLINE',
    href: '/ProductOverviews',
    price: '€25,95',
    imageSrc: ImgProd.GiaccaFront,
    imageAlt: 'TRENCH RELAXED FIT',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Giacca cropped fit realizzata in tessuto di cotone con struttura canvas. Colletto a revers e maniche lunghe con bottone sul polsino. Tasche applicate sul petto e tasche laterali sui fianchi. Perline ricamate combinate',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.GiaccaFront, alt: 'Image 1' },
      { src: ImgProd.GiaccaBack, alt: 'Image 2' },
      { src: ImgProd.GiaccaModel, alt: 'Image 3' },
      { src: ImgProd.GiaccaModel2, alt: 'Image 4' },
    ],
  },
  {
    id: 2,
    name: 'GIUBBOTTO BOMBER IN COTONE',
    href: '/ProductOverviews',
    price: '€25,95',
    imageSrc: ImgProd.GiubbottoFront,
    imageAlt: 'GIUBBOTTO BOMBER IN COTONE',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Giubbotto leggero realizzato in tessuto di cotone. Colletto con finitura a coste elasticizzate e maniche lunghe. Tasche a filetto sui fianchi. Dettaglio di tasca interna. Finiture a coste. Chiusura frontale con',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.GiubbottoFront, alt: 'Image 1' },
      { src: ImgProd.GiubbottoBack, alt: 'Image 2' },
      { src: ImgProd.GiubbottoLat, alt: 'Image 3' },
      { src: ImgProd.GiubbottoModel, alt: 'Image 4' },
    ],
  },
  {
    id: 3,
    name: 'GIACCA CON COLLO A COSTE',
    href: '/ProductOverviews',
    price: '€79,95',
    imageSrc: ImgProd.GiaccaBlueFront,
    imageAlt: 'GIACCA CON COLLO A COSTE',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Giacca relaxed fit realizzata in tessuto misto lana leggermente imbottito all interno. Collo alto a coste in tinta e maniche lunghe. Tasche con chiusura a zip sui fianchi. Finiture a coste. Chiusura frontale con cerniera',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.GiaccaBlueFront, alt: 'Image 1' },
      { src: ImgProd.GiaccaBlueBack, alt: 'Image 2' },
      { src: ImgProd.GiaccaBlueModel, alt: 'Image 3' },
      { src: ImgProd.GiaccaBlueModel2, alt: 'Image 4' },
    ],
  },
  {
    id: 4,
    name: 'GIUBBOTTO BOUCLÉ MISTO LANA',
    href: '/ProductOverviews',
    price: '€79,95',
    imageSrc: ImgProd.BoucleRedFront,
    imageAlt: 'GIUBBOTTO BOUCLÉ MISTO LANA',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'inverno', href: '#' }],
    description: 'Giubbotto relaxed fit realizzato in tessuto misto lana con texture bouclé. Colletto a revers e maniche lunghe con polsino con bottone. Tasche a filetto sui fianchi. Chiusura frontale con cerniera.',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.BoucleRedFront, alt: 'Image 1' },
      { src: ImgProd.BoucleRedBack, alt: 'Image 2' },
      { src: ImgProd.BoucleRedCerc, alt: 'Image 3' },
      { src: ImgProd.BoucleRedModel, alt: 'Image 4' },
    ],
  },
  /* {
    id: 5,
    name: 'GIUBBOTTO BOMBER IN COTONE',
    href: '/ProductOverviews',
    price: '€89,95',
    imageSrc: ImgProd.GiubbottoFront,
    imageAlt: 'TRENCH RELAXED FIT',
    colors: [{ name: 'Red', class: 'bg-red-500', selectedClass: 'ring-red-500' }],
    sizes: [{ name: 'S', inStock: false }, { name: 'M', inStock: true }, { name: 'L', inStock: true }, { name: 'XL', inStock: false }],
    breadcrumbs: [{ id: 1, name: 'Home', href: '/' }, { id: 2, name: 'ProductList', href: '#' }],
    description: 'Giacca cropped fit realizzata in tessuto di cotone con struttura canvas. Colletto a revers e maniche lunghe con bottone sul polsino. Tasche applicate sul petto e tasche laterali sui fianchi. Perline ricamate combinate',
    highlights: ['Feature 1', 'Feature 2'],
    details: 'a contrasto sulla parte posteriore. Chiusura frontale con abbottonatura.',
    images: [
      { src: ImgProd.GiubbottoFront, alt: 'Image 1' },
      { src: ImgProd.GiubbottoBack, alt: 'Image 2' },
      { src: ImgProd.GiubbottoLat, alt: 'Image 3' },
      { src: ImgProd.GiubbottoModel, alt: 'Image 4' },
    ],
  }, */
  // Agrega más productos aquí...
];

export default ProductList;
